name: Deploy Static Website to S3
on:
 push:
   branches:
     - main  # Change to your default branch

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Set up AWS CLI
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

     - name: Deploy to AWS S3
       run: |
         aws s3 sync ./dist s3://ci-cd-bucket-devops-2024 --delete
